export const theme = {
  colors: {
    background: '#0A0A0F',
    surface: '#13131A',
    surfaceAlt: '#1C1C26',
    text: '#F5F5F7',
    textSecondary: '#A1A1AA',
    textTertiary: '#52525B',
    border: '#27272A',
    accent: '#6366F1',
    accentSoft: 'rgba(99, 102, 241, 0.15)',
    onAccent: '#FFFFFF',
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
    destructive: '#EF4444',
    destructiveSoft: 'rgba(239, 68, 68, 0.12)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    '2xl': 32,
    '3xl': 48,
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 8,
    },
  },
  spring: {
    snappy: { damping: 20, stiffness: 300 },
    bouncy: { damping: 12, stiffness: 200 },
  },
  fonts: {
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
  },
  type: {
    display: { fontFamily: 'Inter-Bold', fontSize: 32, lineHeight: 40 },
    title: { fontFamily: 'Inter-Bold', fontSize: 24, lineHeight: 30 },
    heading: { fontFamily: 'Inter-SemiBold', fontSize: 18, lineHeight: 24 },
    subhead: { fontFamily: 'Inter-Medium', fontSize: 16, lineHeight: 22 },
    body: { fontFamily: 'Inter-Regular', fontSize: 15, lineHeight: 22 },
    callout: { fontFamily: 'Inter-Medium', fontSize: 14, lineHeight: 20 },
    caption: { fontFamily: 'Inter-Regular', fontSize: 13, lineHeight: 18 },
    footnote: { fontFamily: 'Inter-Regular', fontSize: 11, lineHeight: 14 },
  },
};